//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eShelvesDesktop {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eShelvesDesktop.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odabir autora je obavezan.
        /// </summary>
        internal static string autor_req {
            get {
                return ResourceManager.GetString("autor_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cijena nije ispravna.
        /// </summary>
        internal static string cijena_err {
            get {
                return ResourceManager.GetString("cijena_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj dana nije ispravan.
        /// </summary>
        internal static string dana_err {
            get {
                return ResourceManager.GetString("dana_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format E-maila nije ispravan.
        /// </summary>
        internal static string email_err {
            get {
                return ResourceManager.GetString("email_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail je obavezan.
        /// </summary>
        internal static string email_req {
            get {
                return ResourceManager.GetString("email_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unos imena je obavezan.
        /// </summary>
        internal static string fname_req {
            get {
                return ResourceManager.GetString("fname_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unos grada je obavezan.
        /// </summary>
        internal static string grad_req {
            get {
                return ResourceManager.GetString("grad_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISBN broj mora imati tačno 13 cifara.
        /// </summary>
        internal static string isbn_err {
            get {
                return ResourceManager.GetString("isbn_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISBN mora biti numerička vrijednost.
        /// </summary>
        internal static string isbn_numb {
            get {
                return ResourceManager.GetString("isbn_numb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISBN broj je obavezan.
        /// </summary>
        internal static string isbn_req {
            get {
                return ResourceManager.GetString("isbn_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimalno jedna kategorija je obavezna.
        /// </summary>
        internal static string kategorije_req {
            get {
                return ResourceManager.GetString("kategorije_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste dodali knjgu.
        /// </summary>
        internal static string knjigaAdd_succ {
            get {
                return ResourceManager.GetString("knjigaAdd_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste dodali korisnika..
        /// </summary>
        internal static string korisnik_succ {
            get {
                return ResourceManager.GetString("korisnik_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odabir kupca obavezan.
        /// </summary>
        internal static string kupac_err {
            get {
                return ResourceManager.GetString("kupac_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste dodali kupca.
        /// </summary>
        internal static string kupac_succ {
            get {
                return ResourceManager.GetString("kupac_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unos prezimena je obavezan.
        /// </summary>
        internal static string lname_req {
            get {
                return ResourceManager.GetString("lname_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unijeli ste pogrešnu lozinku..
        /// </summary>
        internal static string login_pass_err {
            get {
                return ResourceManager.GetString("login_pass_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste dodali narudžbu.
        /// </summary>
        internal static string narudzba_succ {
            get {
                return ResourceManager.GetString("narudzba_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naslov knjige je obavezan.
        /// </summary>
        internal static string naslov_req {
            get {
                return ResourceManager.GetString("naslov_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv kupca je obavezan.
        /// </summary>
        internal static string nazivKupca_req {
            get {
                return ResourceManager.GetString("nazivKupca_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv kategorije je obavezan.
        /// </summary>
        internal static string novaKategorijaNaziv_req {
            get {
                return ResourceManager.GetString("novaKategorijaNaziv_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis je obavezan.
        /// </summary>
        internal static string opis_req {
            get {
                return ResourceManager.GetString("opis_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinka mora imati minimalno 8 karaktera.
        /// </summary>
        internal static string pass_err {
            get {
                return ResourceManager.GetString("pass_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinka je obavezna.
        /// </summary>
        internal static string pass_req {
            get {
                return ResourceManager.GetString("pass_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj prikaza nije ispravan.
        /// </summary>
        internal static string prikazi_err {
            get {
                return ResourceManager.GetString("prikazi_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste  sačuvali podate o proizvodu..
        /// </summary>
        internal static string product_succ {
            get {
                return ResourceManager.GetString("product_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odabir reklame obavezan.
        /// </summary>
        internal static string reklama_err {
            get {
                return ResourceManager.GetString("reklama_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste dodali reklamu.
        /// </summary>
        internal static string reklama_succ {
            get {
                return ResourceManager.GetString("reklama_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spol je obavezan.
        /// </summary>
        internal static string spol_req {
            get {
                return ResourceManager.GetString("spol_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj dana trajanja nije ispravan.
        /// </summary>
        internal static string trajanje_err {
            get {
                return ResourceManager.GetString("trajanje_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL je obavezan.
        /// </summary>
        internal static string url_req {
            get {
                return ResourceManager.GetString("url_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime mora imati minimalno 5 karaktera.
        /// </summary>
        internal static string usern_err {
            get {
                return ResourceManager.GetString("usern_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime je obavezno.
        /// </summary>
        internal static string usern_req {
            get {
                return ResourceManager.GetString("usern_req", resourceCulture);
            }
        }
    }
}
